#!/bin/bash

# Install native dependencies
apt update
apt install -y curl make sudo protobuf-compiler

# Fix certificate authorities on armv7
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Install bagop
curl -L -o /tmp/bagop "https://github.com/pojntfx/bagop/releases/latest/download/bagop.linux-$(uname -m)"
install /tmp/bagop /usr/local/bin

# Install dependencies
USER=root make depend

# Make release
bagop -j "$(nproc)" -b gopojde-daemon -x '(android/*|ios/*|openbsd/mips64|aix/ppc64|js/wasm|plan9/*)' -d out/release/gopojde-daemon -p 'make release-daemon DST=$DST'
bagop -j "$(nproc)" -b gopojde-manager -x '(android/*|ios/*|plan9/*)' -d out/release/gopojde-manager-native -p 'make release-manager-native DST=$DST'
bagop -j "$(nproc)" -b gopojde-companion -x '(android/*|ios/*|plan9/*)' -d out/release/gopojde-companion-native -p 'make release-companion-native DST=$DST'
