name: hydrun CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - id: gopojde-daemon
            command: bagop -j \"\$(nproc)\" -b gopojde-daemon -x '(android/*|ios/*|openbsd/mips64|aix/ppc64|js/wasm|plan9/*)' -d out/release/gopojde-daemon -p 'make release-daemon DST=\$DST'
          - id: gopojde-manager-native
            command: bagop -j \"\$(nproc)\" -b gopojde-manager -x '(android/*|ios/*|plan9/*|aix/ppc64)' -d out/release/gopojde-manager-native -p 'make release-manager-native DST=\$DST'
          - id: gopojde-manager-web
            command: make release-manager-web
          - id: gopojde-manager-web-github-pages
            command: make release-manager-web-github-pages
          - id: gopojde-companion-native
            command: bagop -j \"\$(nproc)\" -b gopojde-companion -x '(android/*|ios/*|plan9/*|aix/ppc64)' -d out/release/gopojde-companion-native -p 'make release-companion-native DST=\$DST'
          - id: gopojde-companion-web
            command: make release-companion-web

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up hydrun
        run: |
          curl -L -o /tmp/hydrun "https://github.com/pojntfx/hydrun/releases/latest/download/hydrun.linux-$(uname -m)"
          sudo install /tmp/hydrun /usr/local/bin
      - name: Build with hydrun
        run: hydrun -o golang "./Hydrunfile && ${{ matrix.target.command }}"
      - name: Fix permissions for output
        run: sudo chown -R $USER .
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.id }}
          path: |
            out/release/gopojde-daemon/*
            out/release/gopojde-manager-web/*
            out/release/gopojde-manager-native/*
            out/release/gopojde-companion-web/*
            out/release/gopojde-companion-native/*
            out/release/gopojde-manager-web-github-pages

  publish-linux:
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download output
        uses: actions/download-artifact@v2
        with:
          path: /tmp/out
      - name: Isolate the GitHub pages build
        run: |
          mkdir -p /tmp/out-github-pages
          mv /tmp/out/gopojde-manager-web-github-pages/* /tmp/out-github-pages
      - name: Publish pre-release to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: unstable
          prerelease: true
          files: |
            /tmp/out/**/*
      - name: Publish release to GitHub releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            /tmp/out/**/*
      - name: Publish release to GitHub pages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: /tmp/out-github-pages
          git-config-name: GitHub Pages Bot
          git-config-email: bot@example.com
